### ISSUE TITLE
Lennysha 

### ISSUE THREAD

**Issue by ayronlee05** [Lani-Skyy/Lani-Skyy#1]
Llamasha ( ͡° ͜ʖ ͡°)

**Comment by Lani-Skyy** [comment]
Crayron :)

**Comment by ayronlee05** [comment]
NO STOP ASKING DINAH TO BLOW SHE NEEDS THERAPY

**Comment by Lani-Skyy** [comment]
OH MY GOD STOP TALKING ABOUT DINAH LEAVE HER ALONEEE
SHE'S A FRICKING TRAIN OKAY-

**Comment by ayronlee05** [comment]
SHE ISNT SOME MORE STOP DOING CHILD LABOUR OK POOR THING

**Comment by ayronlee05** [comment]
Llamasha Ahnoosri :))

**Comment by ayronlee05** [comment]
Ok closed nowww

**Comment by ayronlee05** [comment]
Whoop

**Comment by Lani-Skyy** [comment]
FRICK U

**Comment by ayronlee05** [comment]
Whoop ur ass ( ͡° ͜ʖ ͡°)

**Comment by Lani-Skyy** [comment]
crayon is gay

**Comment by ayronlee05** [comment]
You are too :))

**Comment by Lani-Skyy** [comment]
NUH UH
OK STOP REOPNENING BYEEEE

**Comment by ayronlee05** [comment]
OI
