### ISSUE TITLE
NUH UH

### ISSUE THREAD

**Issue by ayronlee05** [Lani-Skyy/Lani-Skyy#2]
NUH UH
OK STOP REOPNENING BYEEEE

_Originally posted by @Lani-Skyy in https://github.com/Lani-Skyy/Lani-Skyy/issues/1#issuecomment-840953842_

**Comment by ayronlee05** [comment]
Yes u r

**Comment by Lani-Skyy** [comment]
WOI STOP ITTTKTJKJFKKFJAK
If u don't stop it i'm going to send u taht chicken gif

**Comment by ayronlee05** [comment]
> WOI STOP ITTTKTJKJFKKFJAK
> If u don't stop it i'm going to send u taht chicken gif
